config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'

  resources :jobs do
    resources :resumes
  end

  namespace :account do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do

      resources :resumes

      member do
        post :publish
        post :hide
      end

    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :wage_upper_bound, numericality: { greater_than: :wage_lower_bound }
  validates :wage_lower_bound, numericality: { greater_than: 0.0 }
  validates :title, presence: true
  validates :contact, presence: true

  has_many :resumes

  scope :recent, -> {order("created_at DESC")}
  scope :published, -> {where(is_hidden: false)}

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :attachment, presence: true

  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.

  belongs_to :user
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :resumes, dependent: :destroy

  def is_admin?
    is_admin || email == "234@234"
  end
end

app/controllers/account/resumes_controller.rb
class Account::ResumesController < ApplicationController
  before_action :authenticate_user!

  def index
    @resumes = current_user.resumes.order("created_at DESC")
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  before_action :find_job_and_check_permission, only: [:show, :edit, :update, :destroy, :publish, :hide]

  layout "admin"

  def index
    @jobs = Job.all
  end

  def show
    
  end

  def new
    @job = Job.new    
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path, notice: "成功建立新的招聘启示"
    else
      render :new
    end
  end

  def edit
    
  end

  def update

    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "招聘启示已更新"
    else
      render :edit
    end

  end

  def destroy
    @job.destroy
    redirect_to admin_jobs_path, alert: "招聘启示已删除"
  end


  def publish
    if @job.is_hidden
      @job.publish!
      redirect_to admin_jobs_path, notice: "招聘已发布"
    end
  end

  def hide
    unless @job.is_hidden
      @job.hide!
      redirect_to admin_jobs_path, warning: "招聘已隐藏"
    end
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact, :is_hidden)
  end

  def find_job_and_check_permission
    @job = Job.find(params[:id])
  end
  
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout "admin"

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order("created_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :warning, :danger, :info

  def require_is_admin
    unless current_user.is_admin?
      redirect_to root_path, alert: "你没有权限"
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index  
    @jobs = case params[:order]
            when "by_upper_bound"
              Job.all.published.order("wage_upper_bound DESC")
            when "by_lower_bound"
              Job.all.published.order("wage_lower_bound DESC")
            else
              Job.all.published.recent
            end
  end


  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      redirect_to root_path, alert: "你要访问的内容已被隐藏"
    end
  end
  
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])

    if (current_user.resumes & @job.resumes).empty?  # 求交集，以判断是否已经提交过简历
      @resume = Resume.new
    else
      redirect_to root_path, warning: "你已经提交过简历，请勿再次提交"
    end
  end

  def create
    @job = Job.find(params[:job_id])

    if (current_user.resumes & @job.resumes).empty?

      @resume = Resume.new(resume_params)
      @resume.job = @job
      @resume.user = current_user
      if @resume.save
        redirect_to job_path(@job), notice: "简历已成功提交，可在我个人中心里查看编辑"
      else
        render :new
      end

    else
      redirect_to root_path, warning: "你已经提交过简历，请勿再次提交"
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:name, :phone, :email, :attachment)
  end

end

app/helpers/account/resumes_helper.rb
module Account::ResumesHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_time(time)
    time
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning" 
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_description(job)
    job.description
  end

  def render_job_status(job)
    if job.is_hidden
      content_tag(:i, "", class: ["fas", "fa-lock"])
    else
      content_tag(:i, "", class: ["fas", "fa-eye"])
    end
  end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job] do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
    <%= f.input :wage_upper_bound, input_html: { class: "form-control"} %>
    <%= f.input :wage_lower_bound, input_html: { class: "form-control"} %>
    <%= f.input :contact, input_html: { class: "form-control"} %>
    <%= f.input :is_hidden, as: :boolean, label: "隐藏" %>

  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/admin/jobs/_job_item.html.erb
<tr>
  <td><%= render_job_status(job) %></td>
  <td><%= link_to(job.title, admin_job_resumes_path(job)) %></td>
  <td><%= render_time(job.created_at) %></td>
  <td><%= job.resumes.count %></td>
  <td>
    <%= link_to("Edit", edit_admin_job_path(job), class: "btn btn-sm btn-default")%>
    <%= link_to("Delete", admin_job_path(job),    class: "btn btn-sm btn-danger", 
                  method: :delete, data: { confirm: "Are you sure?" } )%> | 
    <% if job.is_hidden %>
      <%= link_to("Publish", publish_admin_job_path(job), method: :post, class: "btn btn-sm btn-info")%>
    <% else %>
      <%= link_to("Hide", hide_admin_job_path(job), method: :post, class: "btn btn-sm btn-warning")%>
    <% end %>
  </td>
</tr>

app/views/admin/jobs/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑招聘</h2>

    <hr>
    
    <%= render "form" %>

</div>

app/views/admin/jobs/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新建招聘", new_admin_job_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>状态</td>
        <td>Title</td>
        <td>创建时间</td>
        <td>简历投递数量</td>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "job_item" , collection: @jobs, as: :job %>
    </tbody>
  </table>
</div>

app/views/admin/jobs/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新建招聘</h2>

    <hr>
    
    <%= render "form" %>

</div>

app/views/admin/jobs/show.html.erb
<div class="col-md-12">

  <h2><%= @job.title %></h2>
  <p><%= @job.description %></p>

</div>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">
                    <%= resume.user.email %>
                </h3>
            </div>

        </div>
    </div>
    <div class="panel-body">
        <div class="trix-content">
            <p> <%= simple_format(resume.phone) %> </p>
        </div>

        <hr>

        <% if resume.attachment.present? %>
          <i class="fa fa-paperclip"> </i>
          <%= link_to("Download Resume", resume.attachment_url) %>
        <% else %>
           No Attachment
        <% end %>
    </div>
</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - 履历列表 </h2>

<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2018 Job Listing - 1
        <br>Design by
        <a href="http://cps.ninja" target=_new>Twentynight</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">Job Listing - 1</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %> </li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% elsif current_user.is_admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("管理员控制面板", admin_jobs_path) %> </li>
              <li> <%= link_to("我的简历", account_resumes_path) %> </li>
              <li class="divider"></li>
              <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("我的简历", account_resumes_path) %> </li>
              <li class="divider"></li>
              <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/common/_sidebar.html.erb
  <div class="col-md-2">
    <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
        <li class="nav-item active"><%= link_to("管理员主页", admin_jobs_path ) %> </li>
        <li class="nav-item"><%= link_to("收到的简历", "" ) %></li>
    </ul>
  </div>

app/views/jobs/_job_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(job.title, job_path(job)) %></td>
  <td><%= job.wage_upper_bound %></td>
  <td><%= job.wage_lower_bound %></td>
  <td><%= render_time(job.created_at) %></td>
</tr>

app/views/jobs/index.html.erb
<div class="col-md-12">

  <!-- 从 Navbar 上改编过来的代码实现排序按钮
  <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle btn btn-default" data-toggle="dropdown">
                排序
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
              <li> <%= link_to("按招聘发布时间降序", jobs_path(order: "by_created_at")) %> </li>
              <li> <%= link_to("按照薪资上限降序", jobs_path(order: "by_upper_bound")) %> </li>
              <li> <%= link_to("按照薪资下限降序", jobs_path(order: "by_lower_bound")) %> </li>
            </ul>
          </li>
      </ul>
    </div>
    -->

    <!-- 下面是官方演示的排序按钮实现方式代码 -->
    <div class="dropdown clearfix pull-right">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        排序
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
          <li>
            <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
          </li>
          <li>
              <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

          </li>
          <li>
            <%= link_to("按照发表时间排序", jobs_path ) %>

          </li>
      </ul>
    </div>
    <!-- 上面是官方演示的排序按钮实现方式代码 -->

  
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>工资上限</td>
        <td>工资下限</td>
        <td>创建时间</td>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "job_item" , collection: @jobs, as: :job %>
    </tbody>
  </table>
</div>

app/views/jobs/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("投简历", new_job_resume_path(@job), class: "btn btn-default pull-right")%>
  </div>

  <h2><%= @job.title %></h2>
  <p><%= @job.description %></p>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>

      <div class="row">
        <%= render "common/sidebar" %>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render "common/footer" %>

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </body>
</html>

app/views/resumes/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>填写简历</h2>

    <hr>
    
    <%= simple_form_for [@job, @resume] do |f| %>
      <div class="form-group">
        <%= f.input :name, label: "姓名", input_html: { class: "form-control"} %>
        <%= f.input :email, label: "邮箱", input_html: { class: "form-control"} %>
        <%= f.input :phone, label: "电话", input_html: { class: "form-control"} %>
        <%= f.input :attachment, label: "上传 PDF 附件" %>
      </div>
      <%= f.submit "确认提交", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
    <% end %>

</div>